# Generated by Django 4.0.3 on 2022-04-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Cliente')),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provedore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=60, verbose_name='Ingrese nombre del proveedor')),
                ('categoria', models.CharField(max_length=60, verbose_name='Ingrese categoria del proveedor')),
                ('direccion', models.CharField(max_length=60, verbose_name='Ingrese la direccion del proveedor')),
                ('telefono_proveedor', models.IntegerField(verbose_name='Ingrese Telefono del proveedor')),
                ('email_proveedor', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Proveedor')),
            ],
        ),
    ]
