# Generated by Django 4.0.3 on 2022-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_musico', models.CharField(max_length=60, verbose_name='Ingrese nombre del musico')),
                ('categoria', models.CharField(max_length=60, verbose_name='Ingrese categoria del musico')),
                ('direccion', models.CharField(max_length=60, verbose_name='Ingrese la direccion del musico')),
                ('telefono_musico', models.IntegerField(verbose_name='Ingrese Telefono del musico')),
                ('email_musico', models.EmailField(max_length=254, verbose_name='Ingrese Correo del musico')),
            ],
        ),
    ]
