# Generated by Django 4.0.3 on 2022-05-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaplicacion', '0002_musico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
