# Generated by Django 4.0.3 on 2022-05-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaplicacion', '0005_direccion_alter_provedore_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audioyvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_audioyvideo', models.CharField(max_length=60, verbose_name='Ingrese nombre del Audio y video')),
                ('categoria_audioyvideo', models.CharField(max_length=60, verbose_name='Ingrese categoria del Audio y video')),
                ('direccion_audioyvideo', models.CharField(max_length=60, verbose_name='Ingrese la direccion del Audio y video')),
                ('telefono_audioyvideo', models.IntegerField(verbose_name='Ingrese Telefono del Audio y video')),
                ('email_audioyvideo', models.EmailField(max_length=254, verbose_name='Ingrese Correo del Audio y video')),
            ],
        ),
        migrations.RenameField(
            model_name='musico',
            old_name='categoria',
            new_name='categoria_musico',
        ),
        migrations.RenameField(
            model_name='musico',
            old_name='direccion',
            new_name='direccion_musico',
        ),
        migrations.RenameField(
            model_name='provedore',
            old_name='categoria',
            new_name='categoria_proveedor',
        ),
        migrations.RenameField(
            model_name='provedore',
            old_name='direccion',
            new_name='direccion_proveedor',
        ),
    ]
